<a href="https://colab.research.google.com/github/shrestha001/fmml2021/blob/main/10_Problem_Solution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
# Madagascar problem

In [19]:
import numpy as np

In [58]:
A = np.array([[20, 122, 20], [35,180, 35],[70, 300, 30],[50, 220, 65]])
x = np.array([[0.05], [0.002], [0.02]])
citizen = np.array([['AAA'],['AAB'],['ACA'],['ABB']])

In [11]:
# 4x3 . 3x1 = 4x1

In [21]:
y = np.matmul(A,x) - 4.0

In [22]:
y

array([[-2.356],
       [-1.19 ],
       [ 0.7  ],
       [ 0.24 ]])

In [23]:
Z = np.hstack((A,y))

In [50]:
def RankArray(A,x):
  y = np.dot(A,x) - 4.0
  L = np.hstack((A,y))
  return L

In [51]:
print (RankArray(A,x))

[[ 2.000e+01  1.220e+02  2.000e+01 -2.356e+00]
 [ 3.500e+01  1.800e+02  3.500e+01 -1.190e+00]
 [ 7.000e+01  3.000e+02  3.000e+01  7.000e-01]
 [ 5.000e+01  2.200e+02  6.500e+01  2.400e-01]]


In [54]:
def covid(A,x):
   Z= RankArray(A,x).transpose()
   return(Z[-1]>0)
 

In [61]:
Z= covid(A,x)
for i in range(len(Z)):
  if (Z[i] == True):
    print('{} citizen is at risk'.format(citizen[i]))
  else:
    print('{} citizen is not at risk'.format(citizen[i]))  

['AAA'] citizen is not at risk
['AAB'] citizen is not at risk
['ACA'] citizen is at risk
['ABB'] citizen is at risk
